MediGuard/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from .views import user_dashboard

app_name = 'MediGuard'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login/', views.login, name='login'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('report/', views.report, name='report'),
    path('<int:report_id>/report_submitted/', views.report_submitted, name='report_submitted'),
    path('report_list/', views.report_list, name='report_list'),
    path('<int:report_id>/report_detail/', views.report_detail, name='report_detail'),
    path('report_list/', views.report_list, name='report_list'),
    path('delete_report/<int:pk>/', views.delete_report, name='delete_report'),
    path('<int:practice_id>/practice_detail/', views.practice_detail, name='practice_detail')
]
    # TODO: Add anonoymous access path

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MediGuard.urls')),
    path('accounts/', include('allauth.urls')),



]

mysite/templates/admin_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h>HELLO</h>
    <p>Hello</p>
</body>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="login-form">
        <h2>Login</h2>
        <!--In the <form method="post">, we need to add such 
            {%  'login-view-url' %}-->
        <form method="post"> 
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
        </form>
    </div>
</body>
</html>

mysite/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="login-form">
        <h2>Login</h2>
        <!--In the <form method="post">, we need to add such 
            %  'login-view-url' %-->
        <form method="post"> 
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username:</label>
                <input type="text" id="username" name="username" required>
            </div>
            <div class="form-group">
                <label for="password">Password:</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="form-group">
                <button type="submit">Login</button>
            </div>
        </form>
    </div>
</body>
</html>

mysite/templates/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit Report</title>
</head>
<body>
    <h1>Submit Report</h1>
    {% if error_message %}
    <p>{{ error_message }}</p>
    {% endif %}
    <form action="{% url 'MediGuard:report' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="whistleblower">Whistleblower:</label><br>
        <input type="text" id="whistleblower" name="whistleblower" required><br><br>

        <label for="description">Description:</label><br>
        <textarea id="description" name="description" rows="4" cols="50" required></textarea><br><br>

        <label for="file">File:</label><br>
        <input type="file" id="file" name="file"><br><br>  <!-- Add file input field -->

        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/templates/report_submitted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report Submitted</title>
</head>
<body>
    <h1>Report Submitted</h1>
    <p>Your report has been submitted successfully!</p>
    <a href="{% url 'MediGuard:user_dashboard' %}">Go back to user dashboard.</a><br><br>
</body>
</html>

mysite/templates/user_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h>HELLO</h>
    <p>Hello</p>
</body>
</html>