MediGuard/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from .views import user_dashboard

app_name = 'MediGuard'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('login/', views.login, name='login'),
    path('accounts/', include('allauth.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('dashboard/', user_dashboard, name='user_dashboard'),
    path('report/', views.report, name='report'),
    path('<int:report_id>/report_submitted/', views.report_submitted, name='report_submitted'),
    path('report_list/', views.report_list, name='report_list'),
    path('<int:report_id>/report_detail/', views.report_detail, name='report_detail'),
    path('report_list/', views.report_list, name='report_list'),
    path('delete_report/<int:pk>/', views.delete_report, name='delete_report'),
    path('<int:practice_id>/practice_detail/', views.practice_detail, name='practice_detail')
]
    # TODO: Add anonoymous access path

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MediGuard.urls')),
    path('accounts/', include('allauth.urls')),



]

MediGuard/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AbstractUser, Permission, Group

class Practice(models.Model):
    STATE_CHOICES=(
        ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'),
        ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'),
        ('HI', 'Hawaiian'), ('ID', 'Idaho'), ('IL', 'Illinois'),  ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'),
        ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'),
        ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'),
        ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'),
        ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'),
        ('WA', 'Washington'), ('WV' , 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    )
    name = models.CharField(max_length=100, default='')
    state = models.CharField(max_length=50, default='', choices=STATE_CHOICES)
    city = models.CharField(max_length=50, default='')
    address = models.CharField(max_length=200, default='')
    zipcode = models.CharField(max_length=10, default='')
    phone = models.CharField(max_length=15, default='', blank=True)
    website = models.URLField(default='', blank=True)
    description = models.TextField(default='', blank=True)

    def __eq__(self, other):
        if not isinstance(other, Practice):
            return False
        return (self.state, self.city, self.address, self.zipcode) == (other.state, other.city, other.address, other.zipcode)

    def __hash__(self):
        return hash((self.state, self.city, self.address, self.zipcode))

    def __str__(self):
        return f"{self.name}"

class Report(models.Model):
    STATUS_CHOICES = (
        ('new', 'New'),
        ('in progress', 'In Progress'),
        ('resolved', 'Resolved'),
    )

    whistleblower = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True )
    subject = models.CharField(max_length=300, default='')
    date_time = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    practice = models.ForeignKey(Practice, on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=20, default= 'New', editable=True)
    notes = models.TextField(default='')

    def __str__(self):
        if self.whistleblower:
            return f"Report by {self.whistleblower.username} - {self.date_time}"
        else:
            return f"Anonymous report - {self.date_time}"


class ReportFile(models.Model):
    report = models.ForeignKey(Report, related_name='files', on_delete=models.CASCADE)
    file = models.FileField(upload_to='report_files/')

    def __str__(self):
        return f"File for report {self.report.id}"


class Profile(AbstractUser):
    ROLES = (
        ('anonymous_user', 'Anonymous'),
        ('common_user', 'Common User'),
        ('site_admin', 'Site Admin'),
        ('django_admin', 'Django Admin'),
    )

    role = models.CharField(max_length=20, choices=ROLES)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    profile_picture = models.ImageField(upload_to='profile_pictures/', blank=True, null=True)
    contact_number = models.CharField(max_length=20, blank=True)
    address = models.CharField(max_length=255, blank=True)

    groups = models.ManyToManyField(Group, related_name='profiles')
    user_permissions = models.ManyToManyField(Permission, related_name='profiles')

    def __str__(self):
        return f"Profile of {self.user.username}"

MediGuard/forms.py
from django import forms
from .models import Profile
from .models import Report
from .models import ReportFile
from .models import Practice


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['role', 'user', 'profile_picture', 'contact_number', 'address']


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['subject', 'description']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ReportForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        report = super(ReportForm, self).save(commit=False)
        # if self.user and not report.whistleblower:
        #     report.whistleblower = self.user
        if commit:
            report.save()
        return report


class ReportFileForm(forms.ModelForm):
    class Meta:
        model = ReportFile
        fields = ['file']


class ResolveForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = ['notes']

    def __init__(self, *args, **kwargs):
        super(ResolveForm, self).__init__(*args, **kwargs)
        self.fields['notes'].required = False

    def save(self, commit=True):
        report = super(ResolveForm, self).save(commit=False)
        if commit:
            report.status = 'Resolved'
            report.save()
        return report


class PracticeForm(forms.ModelForm):
    existing_practices = forms.ModelChoiceField(
        queryset=Practice.objects.all(),
        required=False,
        label="Select a Practice",
        empty_label="My practice is not listed"
    )
    new_practice = forms.CharField(
        max_length=100,
        required=False,
        label="Name of Practice"
    )

    class Meta:
        model = Practice
        fields = ['existing_practices', 'new_practice', 'state', 'city', 'address', 'zipcode', 'phone', 'website']
        labels = {
            'new_practice': "Name of practice, hospital, group, etc.",
            'phone': "Phone number for practice (if applicable)",
            'website': "Website for practice (if applicable)"
        }

    def clean(self):
        cleaned_data = super().clean()
        existing_practice = cleaned_data.get('existing_practices')
        new_practice = cleaned_data.get('new_practice')

        if not existing_practice and not new_practice:
            raise forms.ValidationError("Please select an existing practice or enter a new practice name.")

        if existing_practice and new_practice:
            raise forms.ValidationError(
                "Please select either an existing practice or enter a new practice name, not both.")

        if new_practice:
            if Practice.objects.filter(name__iexact=new_practice).exists():
                raise forms.ValidationError("This practice already exists. Please select it from the dropdown.")

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super(PracticeForm, self).__init__(*args, **kwargs)
        self.fields['phone'].required = False
        self.fields['website'].required = False
        self.fields['state'].required = False
        self.fields['city'].required = False
        self.fields['address'].required = False
        self.fields['zipcode'].required = False


        if 'instance' in kwargs and kwargs['instance']:
            existing_practice = kwargs['instance']
            self.fields['state'].initial = existing_practice.state
            self.fields['city'].initial = existing_practice.city
            self.fields['address'].initial = existing_practice.address
            self.fields['zipcode'].initial = existing_practice.zipcode


    def save(self, commit=True):
        if self.cleaned_data['existing_practices']:
            return self.cleaned_data['existing_practices']

        practice = Practice(
            name=self.cleaned_data['new_practice'],
            state=self.cleaned_data['state'],
            city=self.cleaned_data['city'],
            address=self.cleaned_data['address'],
            zipcode=self.cleaned_data['zipcode'],
            phone=self.cleaned_data['phone'],
            website=self.cleaned_data['website']
        )
        if commit:
            practice.save()
        return practice

MediGuard/views.py
import boto3
import os
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ProfileForm, ReportForm, ResolveForm, ReportFileForm, PracticeForm
from .models import Profile, Report, ReportFile, Practice
from allauth.socialaccount.models import SocialAccount
from django.shortcuts import render



@login_required(login_url='MediGuard:login')
def user_dashboard(request):
    user_groups = request.user.groups.all()
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()
    reports = Report.objects.filter(whistleblower=request.user)

    sort_order = {'New': 1, 'In Progress': 2, 'Resolved': 3}

    reports = sorted(reports, key=lambda x: (sort_order[x.status], x.date_time))


    return render(request, 'user_dashboard.html', {
        'is_siteAdmin': is_siteAdmin,
        'reports': reports,
    })


def home_page(request):
    user_groups = request.user.groups.all()
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()

    return render(request, 'home_page.html', {'is_siteAdmin': is_siteAdmin})


def login(request):
    if request.user.is_authenticated:
        return redirect('')
    else:
        return render(request, 'login.html')




def view_profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request, 'profile.html', {'profile': profile})


@login_required(login_url='MediGuard:login')
def edit_profile(request):
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('view_profile')
    else:
        form = ProfileForm(instance=profile)
    return render(request, 'edit_profile.html', {'form': form})


# NEW REPORT TO PASS AnonymousReportSubmissionTest
def report(request):
    is_siteAdmin = request.user.groups.filter(name='Site Admin').exists() if request.user.is_authenticated else False

    if request.method == 'POST':
        report_form = ReportForm(request.POST, request.FILES)
        practice_form = PracticeForm(request.POST)

        if report_form.is_valid() and practice_form.is_valid():
            new_report = report_form.save(commit=False)
            new_practice = practice_form.save()
            new_practice.save()

            if request.user.is_authenticated:
                new_report.whistleblower = request.user
            new_report.practice = new_practice
            new_report.save()

            files = request.FILES.getlist('file')
            for f in files:
                f = ReportFile(report=new_report, file=f)
                f.save()

            return redirect('MediGuard:report_submitted', report_id = new_report.id)

    else:
        report_form = ReportForm()
        practice_form = PracticeForm()

    return render(request, 'report.html', {
        'report_form': report_form,
        'is_siteAdmin': is_siteAdmin,
        'practice_form': practice_form
    })

def report_submitted(request, report_id):
    user_groups = request.user.groups.all()
    report = Report.objects.get(id=report_id)
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()

    return render(request, 'report_submitted.html', {'is_siteAdmin': is_siteAdmin, 'report': report})


@login_required(login_url='MediGuard:login')
def report_list(request):
    user_groups = request.user.groups.all()
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()
    if is_siteAdmin:
        template_name = 'report_list.html'
        reports = Report.objects.all()
        sort_order = {'New': 1, 'In Progress': 2, 'Resolved': 3}
        reports = sorted(reports, key=lambda x: (sort_order[x.status], x.date_time))
        return render(request, template_name, {'is_siteAdmin': is_siteAdmin, 'reports': reports})
    else:
        return redirect('MediGuard:home_page')






@login_required(login_url='MediGuard:login')
def report_detail(request, report_id):
    user_groups = request.user.groups.all()
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()
    report = Report.objects.get(id=report_id)
    if is_siteAdmin or request.user== report.whistleblower:
        files = ReportFile.objects.filter(report=report)
        if report.status == ('New' or 'new') and is_siteAdmin:
            report.status = 'In Progress'
            report.save()
            return redirect('MediGuard:report_detail', report_id=report_id)
        if request.method == 'POST':
            form = ResolveForm(request.POST)

            if form.is_valid():
                report.notes = form.cleaned_data['notes']
                report.status = 'Resolved'
                report.save()
                return redirect('MediGuard:report_detail', report_id=report_id)
            else:
                return render(request, 'report_detail.html', {'form': form, 'is_siteAdmin': is_siteAdmin, 'report': report})
        else:
            form = ResolveForm()
        return render(request, 'report_detail.html', {'form': form, 'is_siteAdmin': is_siteAdmin, 'report': report, 'files': files})
    else:
        return redirect('MediGuard:home_page')

@login_required(login_url='MediGuard:login')
def delete_report(request, pk):
    report = get_object_or_404(Report, pk=pk)
    report_files = ReportFile.objects.filter(report_id=report.id)
    '''for file in report_files:
        file.delete()'''
    if request.user == report.whistleblower:
        if not ('ON_HEROKU' in os.environ):
            try:
                os.environ.get('AWS_ACCESS_KEY_ID')
                os.environ.get('AWS_SECRET_ACCESS_KEY')
            except:
                import AWS_KEYS
                AWS_ACCESS_KEY_ID = AWS_KEYS.AccessKey
                AWS_SECRET_ACCESS_KEY = AWS_KEYS.SecretAccessKey
        else:
            AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
            AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
        AWS_QUERYSTRING_AUTH: False
        client = boto3.client(
            's3',
            aws_access_key_id=AWS_ACCESS_KEY_ID,
            aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        )
        for file in report_files:
            client.delete_object(Bucket='medi-giard', Key=str(file.file))
        report.delete()
        return redirect('MediGuard:user_dashboard')
    else:
        return HttpResponse("You don't have permission to delete this report.", status=403)


@login_required(login_url='MediGuard:login')
def practice_detail(request, practice_id):
    user_groups = request.user.groups.all()
    is_siteAdmin = user_groups.filter(name='Site Admin').exists()
    practice = Practice.objects.get(id=practice_id)
    reports = Report.objects.filter(practice=practice)
    count = reports.count()
    sort_order = {'New': 1, 'In Progress': 2, 'Resolved': 3}
    reports = sorted(reports, key=lambda x: (sort_order[x.status], x.date_time))

    return render(request, 'practice_detail.html', {'is_siteAdmin': is_siteAdmin, 'practice': practice, 'reports': reports, 'count': count})

MediGuard/templates/footer.html
<footer class="footer">
    <div class="container text-center">
        <span style="color: black;">Disclaimer: This system is a class project and is not actively monitored. Please refrain from submitting any real or sensitive information.</span>
    </div>
</footer>

MediGuard/templates/header.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Your Page Title</title>
    <link rel="stylesheet" href="{% static 'header.css' %}">
</head>
<body>
    <header class="header sticky-top bg-primary py-3">
        <div class="container-fluid">
            <div class="row justify-content-between align-items-center">
                <div class="col-auto logo-container">
                    <a href="{% url 'MediGuard:home_page' %}">
                        <img src="{% static 'images/MediGuard Logo Correct.png' %}" alt="MediGuardLogo" style="height: 125px; width: 125px;">
                    </a>
                    <h1><a class="text-white mb-0" id="home-link" href="{% url 'MediGuard:home_page' %}">MediGuard</a></h1>
                </div>
                {% if is_siteAdmin %}
                <div class="col-auto center-link">
                    <h2><a class="text-white mb-0" id="reportlist-link" href="{% url 'MediGuard:report_list' %}">View All Reports</a></h2>
                </div>
                {% endif %}
                <div class="col-auto">
                    {% if user.is_authenticated %}
                    <div class="dropdown">
                        <button class="btn btn-light dropdown-toggle" type="button" id="account-dropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.username|title }}
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="account-dropdown">
                            <li class="account-item">
                                <a class="btn-primary btn-sm active" href="{% url 'MediGuard:user_dashboard' %}">My Account</a>
                            </li>
                            <li class="logout-item"><form action="{% url 'MediGuard:logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary">Logout</button>
                            </form></li>
                        </ul>
                    </div>
                    {% else %}
                    <a href="{% url 'MediGuard:login' %}" class="btn btn-light">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
</body>
</html>

MediGuard/templates/home_page.html
{% load socialaccount %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
 <html lang="en">
<link rel="stylesheet" href="{% static 'nav.css' %}">

<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Homepage</title>
</head>

<body class="bg-light">
    {% include 'header.html' %}

 <div class="container mt-5" id="report-link">
        <p>If you have witnessed or experienced any form of medical malpractice, please use the button below to report it:</p>
        <a href="{% url 'MediGuard:report' %}" class="btn btn-primary">Report Now</a>
 </div>

 <main class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card border-primary shadow">
                <div class="card-body">
                    <h2 class="card-title text-primary text-center">Support</h2>
                    <p class="card-text text-center">For any inquiries or assistance on what constitutes malpractice, please don't hesitate to contact us.</p>
                    <p class="card-text text-center">For support, please call: <strong>(123) 456-7890</strong></p>
                </div>
            </div>
        </div>
    </div>
 </main>

</body>
   <footer class="footer fixed-bottom">
        {% include 'footer.html' %}
   </footer>
</html>

MediGuard/templates/report.html
{% load static %}
{% load socialaccount %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Submit Report</title>
    <link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body>
    {% include 'header.html' %}
    <div class="container mt-5">
        <h1>Submit Report</h1>
        <p>Please include details regarding your medical malpractice incident. You may additionally upload any supporting documentation/files below.</p>
        {% if error_message %}
        <p class="text-danger">{{ error_message }}</p>
        {% endif %}
        <form action="{% url 'MediGuard:report' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form report_form %}
        <input type="file" name="file" id="file-id" multiple class="form-control-file mt-3">
        <div class="mt-4">
            <h2>Medical Practice Information</h2>
            <p>Please include information about the hospital/practice/facility most closely associated with your report</p>
            {% if practice_form.non_field_errors %}
                <p class="text-danger">{{ practice_form.non_field_errors.as_text }}</p>
            {% endif %}
            {% if practice_form.errors %}
                {% for field in practice_form %}
                    {% for error in field.errors %}
                        <div class="text-danger">
                            {{ error }}
                        </div>
                    {% endfor %}
                {% endfor %}
            {% endif %}
            {{ practice_form.existing_practices.label_tag }}
            {{ practice_form.existing_practices }}
        </div>
        {% if practice_form.existing_practices.value == None %}
            <div id="additional-fields" style="display: block; margin-top: 20px;">
                <div class="mb-3">
                    {{ practice_form.new_practice.label_tag }}
                    {{ practice_form.new_practice }}
                </div>
                <div class="mb-3">
                    {{ practice_form.state.label_tag }}
                    {{ practice_form.state }}
                </div>
                <div class="mb-3">
                    {{ practice_form.city.label_tag }}
                    {{ practice_form.city }}
                </div>
                <div class="mb-3">
                    {{ practice_form.zipcode.label_tag }}
                    {{ practice_form.zipcode }}
                </div>
                <div class="mb-3">
                    {{ practice_form.address.label_tag }}
                    {{ practice_form.address }}
                </div>
                <div class="mb-3">
                    {{ practice_form.phone.label_tag }}
                    {{ practice_form.phone }}
                </div>
                <div class="mb-3">
                    {{ practice_form.website.label_tag }}
                    {{ practice_form.website }}
                </div>
            </div>
        {% endif %}
        <button type="submit" class="btn btn-primary mt-4">Submit</button>
        </form>
    </div>

    <script>
        document.getElementById('id_existing_practices').addEventListener('change', function() {
            var newPracticeFields = document.getElementById('additional-fields');
            if (this.value === '') {
                newPracticeFields.style.display = 'block';
            } else {
                newPracticeFields.style.display = 'none';
            }
        });
    </script>
    <br><br>
    {% include 'footer.html' %}
</body>
</html>

MediGuard/templates/report_detail.html
{% load socialaccount %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report List</title>
    <link rel="stylesheet" href="{% static 'nav.css' %}">
    <style>
        .description {
            word-wrap: break-word;
        }
    </style>
</head>

<body class="bg-light">
    {% include 'header.html' %}
    <div class="container mt-4">
        <h2>{{report.subject}}</h2>
    <div class="row mb-3">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>Report Details</strong>
                </div>
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col"><strong>Whistleblower</strong></div>
                        <div class="col">{{ report.whistleblower|title }}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col"><strong>Date Published</strong></div>
                        <div class="col">{{ report.date_time }}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col"><strong>Status</strong></div>
                        <div class="col">{{ report.status }}</div>
                    </div>
                    <div class="row mb-2">
                        <div class="col"><strong>Medical Practice</strong></div>
                        <div class="col"><a href="{% url 'MediGuard:practice_detail' report.practice.id %}">{{ report.practice }}</a></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>Files Submitted</strong>
                </div>
                <div class="card-body">
                    {% if files %}
                        <ul>
                            {% for f in files %}
                                <li><a href="{{ f.file.url }}">{{ f.file }}</a></li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <p>No files submitted for this report</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <strong>Description</strong>
                </div>
                <div class="card-body">
                    {{ report.description }}
                </div>
            </div>
        </div>
        {% if report.status == 'Resolved' %}
            <div class="row mt-3">
                <div class="col">
                    <div class="card">
                        <div class="card-header">
                            <strong>Resolution Notes</strong>
                        </div>
                        <div class="card-body">
                            {{ report.notes }}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
</div>
    {% if report.status == 'Resolved' %}
    <div class="container-fluid mt-4">
        <p>Report has been resolved.</p>
    </div>
    {% else %}
    {% if is_siteAdmin %}
    <div class="container-fluid mt-4">
        <h3>Update Status</h3>
        <form action="{% url 'MediGuard:report_detail' report.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">Resolve</button>
        </form>
    </div>
    {% endif %}
    {% endif %}
</body>
<footer style="margin-top: 15px; bottom:0; position:relative; width:100%">
        {% include 'footer.html' %}
</footer>
</html>

MediGuard/templates/user_dashboard.html
{% load socialaccount %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Dashboard</title>
    <link rel="stylesheet" href="{% static 'nav.css' %}">
</head>
<body class="bg-light">
        {% include 'header.html' %}


    <div class="container mt-5">
        {% if is_siteAdmin %}
            <h1>Welcome, {{ user.username|title }}!</h1>
            <p>You are a site admin.</p>
        {% else %}
            <h1>Welcome, {{ user.username|title }}!</h1>
        {% endif %}

        <a href="{% url 'MediGuard:report' %}" class="btn btn-primary">Fill out a report</a>

        <div style="padding-left: 15px; padding-right: 15px; padding-top: 15px">
    {% if reports %}
        {% for report in reports %}
            {% if forloop.first or forloop.counter0|divisibleby:3 %}
                <div class="row">
            {% endif %}
            <div class="col-md-4 mb-3">
                <a href="{% url 'MediGuard:report_detail' report.id %}" style="color:black; text-decoration: none">
                <div class="card" style="cursor: pointer; transition: box-shadow 0.3s, transform 0.3s;"
                     onmouseover="this.style.boxShadow='0 4px 8px rgba(3, 138, 255)'; this.style.transform='scale(1.03)';"
                     onmouseout="this.style.boxShadow='none'; this.style.transform='scale(1)';">
                    <div class="card-body">
                        <h5 class="card-title">{{ report.subject|truncatechars:50 }}</h5>
                        <p class="card-text"><strong>Date Published: </strong>{{ report.date_time }}</p>
                        <p class="card-text"><strong>Status: </strong>{{ report.status }}</p>
                        <form action="{% url 'MediGuard:delete_report' report.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
                </a>
            </div>
            {% if forloop.last or forloop.counter|divisibleby:3 %}
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>There are no reports available at this time.</p>
    {% endif %}
    </div>
    </div>

</body>
<footer style="margin-top: 15px; bottom:0; position: relative; width:100%">
        {% include 'footer.html' %}
</footer>
</html>